<project name = "Greyvar-editor" default = "package">
    <property file = "project.properties" />
    <property name = "version" value = "${version.major}.${version.minor}.${version.build}" />

    <target name = "package" depends = "package-jar, package-zip" />

    <target name = "package-jar">
        <jar destfile = "pkg/Greyvar-editor-${version}.jar" basedir = "bin/">
        	<manifest>
        		<attribute name="Main-Class" value = "greyvarEditor.Main" />
        	</manifest>
        </jar>
    </target>

	<target name = "package-zip">
		   <zip destfile = "pkg/Greyvar-editor-${version}.zip">
		    <zipfileset dir = "../../jwrCommonsJava/pkg/">
		    	<include name = "jwrCommonsJava.jar" />
		    </zipfileset>

		    <zipfileset dir = "pkg">
		    	<include name = "Greyvar-editor-${version}.jar" />
		    </zipfileset>
		   </zip>
	</target>
</project>
