syntax = "proto3";

option go_package = "gen/greyvarprotocol";

package greyvarproto;

message ClientRequests {
	RegistrationRequest registrationRequest = 1;
	MoveRequest moveRequest = 2;
	WorldListRequest worldListRequest = 3;
	WorldLoadRequest worldLoadRequest = 4;
}

message MoveRequest {
	int32 playerId = 1;
	int32 x = 2;
	int32 y = 3;
}

message ConnectionRequest {
}

message RegistrationRequest {	
	string username = 1;
}

message WorldListRequest {}

message WorldLoadRequest {
	string worldId = 1;
}
