// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: server_interface.proto

#include "server_interface.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
namespace greyvarproto {
}  // namespace greyvarproto
static constexpr ::PROTOBUF_NAMESPACE_ID::Metadata* file_level_metadata_server_5finterface_2eproto = nullptr;
static constexpr ::PROTOBUF_NAMESPACE_ID::EnumDescriptor const** file_level_enum_descriptors_server_5finterface_2eproto = nullptr;
static constexpr ::PROTOBUF_NAMESPACE_ID::ServiceDescriptor const** file_level_service_descriptors_server_5finterface_2eproto = nullptr;
const ::PROTOBUF_NAMESPACE_ID::uint32 TableStruct_server_5finterface_2eproto::offsets[1] = {};
static constexpr ::PROTOBUF_NAMESPACE_ID::internal::MigrationSchema* schemas = nullptr;
static constexpr ::PROTOBUF_NAMESPACE_ID::Message* const* file_default_instances = nullptr;

const char descriptor_table_protodef_server_5finterface_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\026server_interface.proto\022\014greyvarproto\032\037"
  "client_to_server_messages.proto\032\037server_"
  "to_client_messages.proto2\372\001\n\017ServerInter"
  "face\022N\n\007Connect\022\037.greyvarproto.Connectio"
  "nRequest\032 .greyvarproto.ConnectionRespon"
  "se\"\000\022B\n\013PlayerSetup\022\027.greyvarproto.NewPl"
  "ayer\032\030.greyvarproto.NoResponse\"\000\022S\n\016GetS"
  "erverFrame\022\034.greyvarproto.ClientRequests"
  "\032!.greyvarproto.ServerFrameResponse\"\000b\006p"
  "roto3"
  ;
static const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable*const descriptor_table_server_5finterface_2eproto_deps[2] = {
  &::descriptor_table_client_5fto_5fserver_5fmessages_2eproto,
  &::descriptor_table_server_5fto_5fclient_5fmessages_2eproto,
};
static ::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase*const descriptor_table_server_5finterface_2eproto_sccs[1] = {
};
static ::PROTOBUF_NAMESPACE_ID::internal::once_flag descriptor_table_server_5finterface_2eproto_once;
const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_server_5finterface_2eproto = {
  false, false, descriptor_table_protodef_server_5finterface_2eproto, "server_interface.proto", 365,
  &descriptor_table_server_5finterface_2eproto_once, descriptor_table_server_5finterface_2eproto_sccs, descriptor_table_server_5finterface_2eproto_deps, 0, 2,
  schemas, file_default_instances, TableStruct_server_5finterface_2eproto::offsets,
  file_level_metadata_server_5finterface_2eproto, 0, file_level_enum_descriptors_server_5finterface_2eproto, file_level_service_descriptors_server_5finterface_2eproto,
};

// Force running AddDescriptors() at dynamic initialization time.
static bool dynamic_init_dummy_server_5finterface_2eproto = (static_cast<void>(::PROTOBUF_NAMESPACE_ID::internal::AddDescriptors(&descriptor_table_server_5finterface_2eproto)), true);
namespace greyvarproto {

// @@protoc_insertion_point(namespace_scope)
}  // namespace greyvarproto
PROTOBUF_NAMESPACE_OPEN
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
