name: Go

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: bufbuild/buf-action@v1
        with:
          setup_only: true

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: server/go.mod

      - name: Generate protocol
        run: make proto

      - name: Test
        run: make test

      - name: Build server
        run: make server
